apiVersion: v1
kind: Service
metadata:
  name: airbnb-app
  labels:
    app: airbnb-app
spec:
  type: NodePort
  selector:
    app: airbnb-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
